//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDBasicsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class playersSeason
    {
        public int Id { get; set; }
        public Nullable<short> Year { get; set; }
        public string Player { get; set; }
        public Nullable<float> G { get; set; }
        public Nullable<float> PER { get; set; }
        public Nullable<float> FG_ { get; set; }
        public Nullable<float> TRB { get; set; }
        public Nullable<float> AST { get; set; }
        public Nullable<float> STL { get; set; }
        public Nullable<float> BLK { get; set; }
        public Nullable<float> TOV { get; set; }
        public Nullable<float> PF { get; set; }
        public Nullable<float> PTS { get; set; }
        public Nullable<float> pts_avg { get; set; }
        public Nullable<float> ast_avg { get; set; }
        public Nullable<float> trb_avg { get; set; }
        public Nullable<decimal> blk_avg { get; set; }
        public Nullable<decimal> stl_avg { get; set; }
        public Nullable<decimal> pf_avg { get; set; }
    }
}
