//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDBasicsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class playerAverage
    {
        public int id { get; set; }
        public string Player { get; set; }
        public Nullable<decimal> pts_avg { get; set; }
        public Nullable<decimal> assists_avg { get; set; }
        public Nullable<decimal> rebounds_avg { get; set; }
        public Nullable<decimal> blocks_avg { get; set; }
        public Nullable<decimal> steals_avg { get; set; }
        public Nullable<decimal> fouls_avg { get; set; }
        public Nullable<decimal> PER { get; set; }
        public Nullable<decimal> games_per_season { get; set; }
    }
}
